# Change these first
owner: abingdonflooring # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Alliance Portal
    url: https://portal.alliancefdl.co.uk/alliance/
  - name: Alliance API  
    url: http://109.239.83.34
  - name: Customer Portal
    url: https://portal.abingdonflooring.co.uk/
  - name: VPN
    url: https://VPN.abingdonflooring.co.uk
  - name: Customer Warranty registration
    url: https://stainfreeforlife.com/
  - name: AFL Homepage
    url: https://www.abingdonflooring.co.uk
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://www.abingdonflooring.co.uk/wp-content/uploads/xGroup-110.png.pagespeed.ic.hUVL0CdV38.png
  name: Abingdon Flooring Service Status
  introTitle: "Abingdon Flooring Service Status"
  introMessage: Abingdon Flooring Service Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Please contact the helpdesk if you have issues
